DESC EMPLOYEE;
DESC DESIGNATION;
DESC DEPARTMENT;

SELECT * FROM EMPLOYEE WHERE DEPT_CODE IS NULL;

SELECT * FROM EMPLOYEE WHERE BASIC = 0;

SELECT * FROM EMPLOYEE WHERE BASIC IS NULL;

SELECT AVG(BASIC) FROM EMPLOYEE;